import { transform } from '@formatjs/ts-transformer';
import ReactRefreshWebpackPlugin from '@pmmmwh/react-refresh-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
import path from 'path';
import ReactRefreshTypeScript from 'react-refresh-typescript';
import { Configuration } from 'webpack';
import RemoveEmptyScriptsPlugin from 'webpack-remove-empty-scripts';

import {
  getDevServer,
  getFileLoaderRules,
  getImageMinimizer,
  getStylesheetRule
} from './common-config';

import HtmlWebpackPlugin from 'html-webpack-plugin';
import getLocalAliases from './utils/getLocalAliases';
import getPublicPath from './utils/getPublicPath';
import getResolvedSiteConfigPath from './utils/getResolvedSiteConfigPath';

const aliases = getLocalAliases();
const resolvedSiteConfigPath = getResolvedSiteConfigPath('shell/site.config.dev.tsx');

const config: Configuration = {
  entry: {
    app: path.resolve(process.cwd(), 'shell/site'),
  },
  output: {
    path: path.resolve(process.cwd(), './dist'),
    publicPath: getPublicPath(),
  },
  resolve: {
    alias: {
      ...aliases,
      'site.config': resolvedSiteConfigPath,
      '@src': path.resolve(process.cwd(), 'src'),
    },
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
  },
  mode: 'development',
  devtool: 'eval-source-map',
  module: {
    rules: [
      {
        test: /\.(js|jsx|ts|tsx)$/,
        include: [
          /shell/,
          /runtime/,
          path.resolve(process.cwd(), 'types'),
          resolvedSiteConfigPath,
        ],
        use: {
          loader: require.resolve('ts-loader'),
          options: {
            transpileOnly: true,
            compilerOptions: {
              noEmit: false,
            },
            getCustomTransformers() {
              return {
                before: [
                  transform({
                    overrideIdFn: '[sha512:contenthash:base64:6]',
                  }),
                  ReactRefreshTypeScript()
                ],
              };
            },
          },
        },
      },
      getStylesheetRule('dev'),
      ...getFileLoaderRules(),
    ],
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
    },
    minimizer: getImageMinimizer(),
  },
  // Specify additional processing or side-effects done on the Webpack output bundles as a whole.
  plugins: [
    // RemoveEmptyScriptsPlugin get rid of empty scripts generated by webpack when using mini-css-extract-plugin
    // This helps to clean up the final bundle application
    // See: https://www.npmjs.com/package/webpack-remove-empty-scripts#usage-with-mini-css-extract-plugin
    new RemoveEmptyScriptsPlugin(),
    // Writes the extracted CSS from each entry to a file in the output directory.
    new MiniCssExtractPlugin({
      filename: '[name].css',
    }),
    new HtmlWebpackPlugin({
      inject: true, // Appends script tags linking to the webpack bundles at the end of the body
      template: path.resolve(process.cwd(), 'shell/public/index.html'),
      chunks: ['app'],
    }),
    new ReactRefreshWebpackPlugin(),
    new ForkTsCheckerWebpackPlugin(),
  ],
  // This configures webpack-dev-server which serves bundles from memory and provides live
  // reloading.

  devServer: getDevServer(),

  // Limit the number of watched files to avoid `inotify` resource starvation.
  watchOptions: {
    ignored: /node_modules/
  }
};

export default config;
