import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
import path from 'path';
import TsconfigPathsPlugin from 'tsconfig-paths-webpack-plugin';
import { Configuration } from 'webpack';
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';
import RemoveEmptyScriptsPlugin from 'webpack-remove-empty-scripts';

import {
  getCodeRules,
  getFileLoaderRules,
  getHtmlWebpackPlugin,
  getImageMinimizer,
  getStylesheetRule
} from './common-config';

import getPublicPath from './utils/getPublicPath';
import getResolvedSiteConfigPath from './utils/getResolvedSiteConfigPath';

const resolvedSiteConfigPath = getResolvedSiteConfigPath('site.config.build.tsx');

const config: Configuration = {
  mode: 'production',
  devtool: 'source-map',
  entry: {
    app: '@openedx/frontend-base/shell/site',
  },
  output: {
    filename: '[name].[chunkhash].js',
    path: path.resolve(process.cwd(), 'dist'),
    publicPath: getPublicPath(),
    clean: true, // Clean the output directory before emit.
  },
  resolve: {
    alias: {
      'site.config': resolvedSiteConfigPath,
    },
    plugins: [
      new TsconfigPathsPlugin({
        configFile: path.resolve(process.cwd(), 'tsconfig.json'),
        extensions: ['.ts', '.tsx', '.js', '.jsx'],
      }),
    ],
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
  },
  module: {
    rules: [
      ...getCodeRules('production', resolvedSiteConfigPath),
      getStylesheetRule('production'),
      ...getFileLoaderRules(),
    ],
  },
  // Extract common modules among all chunks to one common chunk and extract the Webpack runtime to a single runtime chunk.
  optimization: {
    runtimeChunk: 'single',
    splitChunks: {
      chunks: 'all',
    },
    minimizer: getImageMinimizer(),
  },
  // Specify additional processing or side-effects done on the Webpack output bundles as a whole.
  plugins: [
    // RemoveEmptyScriptsPlugin get rid of empty scripts generated by webpack when using mini-css-extract-plugin
    // This helps to clean up the final bundle application
    // See: https://www.npmjs.com/package/webpack-remove-empty-scripts#usage-with-mini-css-extract-plugin

    new RemoveEmptyScriptsPlugin(),
    // Writes the extracted CSS from each entry to a file in the output directory.
    new MiniCssExtractPlugin({
      filename: '[name].[chunkhash].css',
    }),
    getHtmlWebpackPlugin(),
    new ForkTsCheckerWebpackPlugin(),
    new BundleAnalyzerPlugin({
      analyzerMode: 'static',
      openAnalyzer: false,
    }),
  ],
};

export default config;
